#!/bin/bash

echo "🚀 CONFIGURAÇÃO GIT DEPLOY HOSTINGER"
echo "===================================="
echo "Domínio: connectia.agenciapixel.digital"
echo ""

# Cores
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}✅ CONFIGURAÇÃO PARA GIT DEPLOY DA HOSTINGER${NC}"
echo ""

echo -e "${BLUE}📋 O que foi configurado:${NC}"
echo "✅ Build script para produção"
echo "✅ Arquivos .htaccess para React Router"
echo "✅ Estrutura otimizada para Hostinger"
echo "✅ GitHub Actions (opcional)"
echo ""

echo -e "${YELLOW}🚀 PASSO 1: CONFIGURAR NO HOSTINGER${NC}"
echo ""
echo -e "${BLUE}1. Acesse o hPanel da Hostinger:${NC}"
echo "   https://hpanel.hostinger.com/"
echo ""
echo -e "${BLUE}2. Vá em Advanced → Git Version Control${NC}"
echo ""
echo -e "${BLUE}3. Configure:${NC}"
echo "   - Repository URL: https://github.com/SEU_USUARIO/connect-ia.git"
echo "   - Branch: main"
echo "   - Deploy Directory: public_html"
echo "   - Auto Deploy: ✅ Ativado"
echo "   - Build Command: npm install && npm run build"
echo "   - Deploy Command: cp -r dist/* public_html/"
echo ""

echo -e "${YELLOW}🚀 PASSO 2: CONFIGURAR GITHUB${NC}"
echo ""
echo -e "${BLUE}1. Crie repositório no GitHub:${NC}"
echo "   - Nome: connect-ia"
echo "   - Visibilidade: Private (recomendado)"
echo ""
echo -e "${BLUE}2. Faça push do código:${NC}"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial commit'"
echo "   git branch -M main"
echo "   git remote add origin https://github.com/SEU_USUARIO/connect-ia.git"
echo "   git push -u origin main"
echo ""

echo -e "${YELLOW}🚀 PASSO 3: TESTAR DEPLOY${NC}"
echo ""
echo -e "${BLUE}1. Após configurar, faça um pequeno teste:${NC}"
echo "   - Edite algum arquivo"
echo "   - git add ."
echo "   - git commit -m 'Test deploy'"
echo "   - git push"
echo ""
echo -e "${BLUE}2. Acesse o hPanel e veja o deploy automático${NC}"
echo ""
echo -e "${BLUE}3. Teste o site: https://connectia.agenciapixel.digital${NC}"
echo ""

echo -e "${GREEN}🎉 VANTAGENS DO GIT DEPLOY HOSTINGER:${NC}"
echo "✅ Deploy automático a cada push"
echo "✅ Build na nuvem da Hostinger"
echo "✅ Sem problemas de conexão FTP"
echo "✅ Rollback fácil"
echo "✅ Histórico de deploys"
echo "✅ Mais confiável que FTP"
echo ""

echo -e "${BLUE}📁 ESTRUTURA DO PROJETO:${NC}"
echo "✅ package.json (dependências)"
echo "✅ vite.config.ts (configuração build)"
echo "✅ src/ (código fonte)"
echo "✅ public/ (arquivos estáticos)"
echo "✅ .htaccess (configuração servidor)"
echo "✅ .github/workflows/ (GitHub Actions opcional)"
echo ""

echo -e "${YELLOW}💡 DICA IMPORTANTE:${NC}"
echo "O Git Deploy da Hostinger fará:"
echo "1. npm install (instalar dependências)"
echo "2. npm run build (build do projeto)"
echo "3. cp -r dist/* public_html/ (copiar arquivos)"
echo ""
echo "Isso garante que sempre terá os arquivos corretos!"
echo ""

echo -e "${GREEN}🚀 PRÓXIMO PASSO:${NC}"
echo "Configure o Git Deploy no hPanel da Hostinger!"
