#!/bin/bash

echo "🎯 CONFIGURAÇÃO WHATSAPP + INSTAGRAM INBOX"
echo "==========================================="
echo ""

# Cores
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}✅ PRODUTOS NECESSÁRIOS:${NC}"
echo ""
echo -e "${BLUE}MANTER:${NC}"
echo "✅ Login do Facebook para Empresas (essencial)"
echo "✅ WhatsApp (principal canal)"
echo "✅ Instagram (inbox para atendimento)"
echo ""
echo -e "${RED}REMOVER:${NC}"
echo "❌ Messenger (não necessário)"
echo ""

echo -e "${GREEN}🔧 OTIMIZAÇÃO NO META FOR DEVELOPERS:${NC}"
echo ""
echo -e "${YELLOW}PASSO 1: Remover Messenger${NC}"
echo "1. Acesse: https://developers.facebook.com/"
echo "2. Vá em: Products → Messenger"
echo "3. Clique: Remove Product"
echo "4. Confirme a remoção"
echo ""

echo -e "${YELLOW}PASSO 2: Verificar WhatsApp${NC}"
echo "1. Vá em: Products → WhatsApp"
echo "2. Verifique se está ativo"
echo "3. Configure as permissões necessárias"
echo ""

echo -e "${YELLOW}PASSO 3: Verificar Instagram${NC}"
echo "1. Vá em: Products → Instagram Basic Display"
echo "2. Verifique se está ativo"
echo "3. Configure as permissões necessárias"
echo ""

echo -e "${GREEN}🎯 PERMISSÕES NECESSÁRIAS:${NC}"
echo ""
echo -e "${BLUE}WhatsApp Business API:${NC}"
echo "• whatsapp_business_management"
echo "• whatsapp_business_messaging"
echo "• pages_show_list"
echo "• pages_messaging"
echo ""

echo -e "${BLUE}Instagram Basic Display:${NC}"
echo "• instagram_basic"
echo "• instagram_manage_messages"
echo "• pages_show_list"
echo "• pages_messaging"
echo ""

echo -e "${BLUE}Facebook Login:${NC}"
echo "• email"
echo "• public_profile"
echo "• pages_show_list"
echo ""

echo -e "${GREEN}📱 CONFIGURAÇÃO DOS CANAIS:${NC}"
echo ""

echo -e "${BLUE}1. 🟢 WHATSAPP BUSINESS${NC}"
echo ""
echo "Credenciais Necessárias:"
echo "• Phone Number ID: 123456789012345"
echo "• Business Account ID: 987654321098765"
echo "• Access Token: EAAG..."
echo "• Verify Token: meu_token_seguro_123"
echo ""
echo "Webhook URL:"
echo "https://bjsuujkbrhjhuyzydxbr.supabase.co/functions/v1/whatsapp-webhook"
echo ""

echo -e "${BLUE}2. 🟢 INSTAGRAM INBOX${NC}"
echo ""
echo "Credenciais Necessárias:"
echo "• Access Token: INSTAGRAM_ACCESS_TOKEN"
echo "• Page ID: INSTAGRAM_PAGE_ID"
echo ""
echo "Webhook URL:"
echo "https://bjsuujkbrhjhuyzydxbr.supabase.co/functions/v1/instagram-webhook"
echo ""

echo -e "${GREEN}🔗 INTEGRAÇÃO NO SISTEMA:${NC}"
echo ""

echo -e "${YELLOW}WhatsApp Setup:${NC}"
echo "1. Abra Connect IA"
echo "2. Vá em: Integrações → WhatsApp"
echo "3. Clique: 'Conectar Canal WhatsApp'"
echo "4. Preencha o formulário:"
echo "   Nome do Canal: WhatsApp Vendas"
echo "   Phone Number ID: 123456789012345"
echo "   Business Account ID: 987654321098765"
echo "   Access Token: EAAG..."
echo "   Verify Token: meu_token_seguro_123"
echo ""

echo -e "${YELLOW}Instagram Setup:${NC}"
echo "1. Vá em: Integrações → Instagram"
echo "2. Clique: 'Conectar Canal Instagram'"
echo "3. Preencha o formulário:"
echo "   Nome do Canal: Instagram Inbox"
echo "   Access Token: [Instagram Access Token]"
echo "   Page ID: [Instagram Page ID]"
echo ""

echo -e "${GREEN}📊 FUNCIONALIDADES DISPONÍVEIS:${NC}"
echo ""

echo -e "${BLUE}WhatsApp Business:${NC}"
echo "✅ Envio de mensagens de texto"
echo "✅ Envio de imagens e documentos"
echo "✅ Mensagens template (aprovadas pelo Meta)"
echo "✅ Webhook para receber mensagens"
echo "✅ Respostas automáticas via IA"
echo "✅ Campanhas de marketing"
echo ""

echo -e "${BLUE}Instagram Inbox:${NC}"
echo "✅ Envio de mensagens diretas"
echo "✅ Envio de mídia (imagens, vídeos)"
echo "✅ Webhook para receber mensagens"
echo "✅ Respostas automáticas via IA"
echo "✅ Gestão de conversas"
echo "✅ Integração com CRM"
echo ""

echo -e "${GREEN}🎯 FLUXO DE ATENDIMENTO:${NC}"
echo ""
echo -e "${YELLOW}Cenário 1: Cliente envia mensagem no WhatsApp${NC}"
echo "1. Webhook recebe a mensagem"
echo "2. Sistema identifica o contato"
echo "3. IA gera resposta automática"
echo "4. Atendente pode intervir se necessário"
echo "5. Conversa fica salva no CRM"
echo ""

echo -e "${YELLOW}Cenário 2: Cliente envia mensagem no Instagram${NC}"
echo "1. Webhook recebe a mensagem"
echo "2. Sistema identifica o contato"
echo "3. IA gera resposta automática"
echo "4. Atendente pode intervir se necessário"
echo "5. Conversa fica salva no CRM"
echo ""

echo -e "${GREEN}📋 CHECKLIST DE CONFIGURAÇÃO:${NC}"
echo ""
echo -e "${BLUE}Meta for Developers:${NC}"
echo "[ ] Remover produto Messenger"
echo "[ ] Verificar WhatsApp ativo"
echo "[ ] Verificar Instagram Basic Display ativo"
echo "[ ] Configurar webhook do WhatsApp"
echo "[ ] Configurar webhook do Instagram"
echo "[ ] Verificar permissões necessárias"
echo ""

echo -e "${BLUE}Sistema Connect IA:${NC}"
echo "[ ] Conectar canal WhatsApp"
echo "[ ] Conectar canal Instagram"
echo "[ ] Testar envio de mensagens"
echo "[ ] Verificar recebimento de mensagens"
echo "[ ] Configurar respostas automáticas"
echo "[ ] Testar integração com CRM"
echo ""

echo -e "${GREEN}🧪 TESTES DE FUNCIONALIDADE:${NC}"
echo ""
echo -e "${YELLOW}Teste WhatsApp:${NC}"
echo "curl -X POST https://bjsuujkbrhjhuyzydxbr.supabase.co/functions/v1/whatsapp-send-message \\"
echo "  -H \"Authorization: Bearer YOUR_SUPABASE_ANON_KEY\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"to\": \"5511999999999\", \"message\": \"Teste WhatsApp\", \"channelId\": \"your_channel_id\"}'"
echo ""

echo -e "${YELLOW}Teste Instagram:${NC}"
echo "curl -X POST https://bjsuujkbrhjhuyzydxbr.supabase.co/functions/v1/instagram-send-message \\"
echo "  -H \"Authorization: Bearer YOUR_SUPABASE_ANON_KEY\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"to\": \"instagram_user_id\", \"message\": \"Teste Instagram\", \"channelId\": \"your_channel_id\"}'"
echo ""

echo -e "${GREEN}⚠️ PROBLEMAS COMUNS E SOLUÇÕES:${NC}"
echo ""
echo -e "${RED}WhatsApp:${NC}"
echo "• Erro: Invalid access token"
echo "  Solução: Verificar se o token está correto e não expirou"
echo ""
echo "• Erro: Phone number not found"
echo "  Solução: Verificar o Phone Number ID no Meta"
echo ""

echo -e "${RED}Instagram:${NC}"
echo "• Erro: Instagram access token invalid"
echo "  Solução: Verificar se o token do Instagram está correto"
echo ""
echo "• Erro: Page not found"
echo "  Solução: Verificar se a página do Instagram está conectada"
echo ""

echo -e "${GREEN}📈 BENEFÍCIOS DA CONFIGURAÇÃO:${NC}"
echo ""
echo -e "${BLUE}WhatsApp + Instagram:${NC}"
echo "🎯 Cobertura completa dos principais canais"
echo "📱 Atendimento unificado em uma plataforma"
echo "🤖 IA automatizada para ambos os canais"
echo "📊 CRM integrado para todos os contatos"
echo "🚀 Escalabilidade para crescimento"
echo ""

echo -e "${BLUE}Otimização:${NC}"
echo "✅ Menos produtos = aprovação mais rápida"
echo "✅ Foco nos canais que realmente usa"
echo "✅ Manutenção simplificada"
echo "✅ Menos complexidade técnica"
echo ""

echo -e "${GREEN}🎯 PRÓXIMOS PASSOS:${NC}"
echo ""
echo -e "${YELLOW}1. Otimizar no Meta:${NC}"
echo "• Remover Messenger"
echo "• Verificar WhatsApp e Instagram ativos"
echo "• Configurar webhooks"
echo ""

echo -e "${YELLOW}2. Configurar no Sistema:${NC}"
echo "• Conectar canal WhatsApp"
echo "• Conectar canal Instagram"
echo "• Testar funcionalidades"
echo ""

echo -e "${YELLOW}3. Configurar IA:${NC}"
echo "• Criar agentes de IA"
echo "• Configurar respostas automáticas"
echo "• Treinar para ambos os canais"
echo ""

echo -e "${GREEN}🎉 CONFIGURAÇÃO OTIMIZADA!${NC}"
echo ""
echo "Agora você tem os dois principais canais de atendimento"
echo "configurados de forma eficiente e com menos complexidade"
echo "para aprovação no Meta."
