#!/bin/bash

echo "🔗 CONFIGURAÇÃO URLs META FOR DEVELOPERS"
echo "======================================="
echo ""

# Cores
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}✅ PÁGINA DE EXCLUSÃO DE DADOS CRIADA!${NC}"
echo ""

echo -e "${BLUE}📄 ARQUIVOS CRIADOS:${NC}"
echo "• public/data-deletion.html - Instruções de exclusão de dados"
echo "• public/privacy-policy.html - Atualizada com referência à exclusão"
echo "• dist/data-deletion.html - Copiado para deploy"
echo "• dist/privacy-policy.html - Atualizada para deploy"
echo ""

echo -e "${YELLOW}🔗 URLs PARA CONFIGURAR NO META FOR DEVELOPERS:${NC}"
echo ""
echo -e "${GREEN}1. Política de Privacidade:${NC}"
echo "   https://connectia.agenciapixel.digital/privacy-policy.html"
echo ""
echo -e "${GREEN}2. Termos de Uso:${NC}"
echo "   https://connectia.agenciapixel.digital/terms.html"
echo ""
echo -e "${GREEN}3. Instruções de Exclusão de Dados:${NC}"
echo "   https://connectia.agenciapixel.digital/data-deletion.html"
echo ""

echo -e "${BLUE}📋 CONFIGURAÇÃO NO META FOR DEVELOPERS:${NC}"
echo ""

echo -e "${YELLOW}1. ACESSAR CONFIGURAÇÕES DO APP:${NC}"
echo "   • Vá para: https://developers.facebook.com/"
echo "   • Login com sua conta"
echo "   • Selecione: Connect IA (ID: 670209849105494)"
echo "   • Navegue para: App Dashboard → Configurações → Básico"
echo ""

echo -e "${YELLOW}2. CONFIGURAR POLÍTICA DE PRIVACIDADE:${NC}"
echo "   • Campo: 'Política de Privacidade'"
echo "   • URL: https://connectia.agenciapixel.digital/privacy-policy.html"
echo ""

echo -e "${YELLOW}3. CONFIGURAR TERMOS DE USO:${NC}"
echo "   • Campo: 'Termos de Uso' ou 'Terms of Service'"
echo "   • URL: https://connectia.agenciapixel.digital/terms.html"
echo ""

echo -e "${YELLOW}4. CONFIGURAR EXCLUSÃO DE DADOS:${NC}"
echo "   • Campo: 'URL de instruções de exclusão de dados'"
echo "   • Campo: 'Data Deletion Instructions URL'"
echo "   • URL: https://connectia.agenciapixel.digital/data-deletion.html"
echo ""

echo -e "${YELLOW}5. SALVAR CONFIGURAÇÕES:${NC}"
echo "   • Clique em 'Salvar Alterações'"
echo "   • Aguarde confirmação"
echo ""

echo -e "${BLUE}🎯 CONTEÚDO DA PÁGINA DE EXCLUSÃO:${NC}"
echo ""
echo "A página de exclusão inclui:"
echo "• ✅ Definição de dados do usuário"
echo "• ✅ Instruções passo a passo"
echo "• ✅ Modelo de email para solicitação"
echo "• ✅ Cronograma do processo (7-10 dias)"
echo "• ✅ O que será excluído"
echo "• ✅ O que NÃO será excluído"
echo "• ✅ Exclusão de dados de terceiros (Meta, WhatsApp, Instagram)"
echo "• ✅ Alternativas à exclusão total"
echo "• ✅ Direitos legais (LGPD)"
echo "• ✅ Contato e suporte"
echo "• ✅ Dúvidas frequentes"
echo ""

echo -e "${BLUE}📱 ESPECÍFICO PARA META INTEGRATION:${NC}"
echo ""
echo "A página cobre especificamente:"
echo "• ✅ Exclusão de dados do WhatsApp Business"
echo "• ✅ Exclusão de dados do Instagram"
echo "• ✅ Exclusão de dados do Facebook/Meta"
echo "• ✅ Tokens de acesso e integrações"
echo "• ✅ Mensagens e histórico de conversas"
echo "• ✅ Configurações de canais"
echo ""

echo -e "${GREEN}✅ VALIDAÇÃO DAS URLs:${NC}"
echo ""
echo "Teste se as URLs estão funcionando:"
echo ""

echo -e "${YELLOW}# Teste Política de Privacidade:${NC}"
echo "curl -I https://connectia.agenciapixel.digital/privacy-policy.html"
echo ""

echo -e "${YELLOW}# Teste Termos de Uso:${NC}"
echo "curl -I https://connectia.agenciapixel.digital/terms.html"
echo ""

echo -e "${YELLOW}# Teste Exclusão de Dados:${NC}"
echo "curl -I https://connectia.agenciapixel.digital/data-deletion.html"
echo ""

echo -e "${BLUE}🔍 VERIFICAÇÃO NO META:${NC}"
echo ""
echo "Após configurar, verifique:"
echo "• ✅ Todas as URLs retornam status 200"
echo "• ✅ Conteúdo carrega corretamente"
echo "• ✅ Páginas estão em português"
echo "• ✅ Cobertura completa de dados do Meta"
echo "• ✅ Instruções claras de exclusão"
echo "• ✅ Conformidade com LGPD"
echo ""

echo -e "${YELLOW}⚠️  REQUISITOS DO META:${NC}"
echo ""
echo "Para aprovação do app, o Meta exige:"
echo "• ✅ Política de Privacidade válida e acessível"
echo "• ✅ Termos de Uso claros"
echo "• ✅ URL de instruções de exclusão de dados"
echo "• ✅ Conteúdo em português (idioma do app)"
echo "• ✅ Cobertura específica de dados do Meta"
echo "• ✅ Processo claro de exclusão"
echo "• ✅ Informações de contato"
echo ""

echo -e "${GREEN}🎉 CONFIGURAÇÃO COMPLETA!${NC}"
echo ""
echo -e "${BLUE}📋 PRÓXIMOS PASSOS:${NC}"
echo "1. ✅ Fazer commit e push dos arquivos"
echo "2. ⏳ Aguardar deploy automático (2-3 minutos)"
echo "3. 🔗 Configurar todas as URLs no Meta for Developers"
echo "4. ✅ Verificar se URLs estão acessíveis"
echo "5. 📝 Submeter app para revisão do Meta"
echo ""

echo -e "${YELLOW}🌐 LINKS PARA CONFIGURAÇÃO:${NC}"
echo ""
echo "• Meta for Developers: https://developers.facebook.com/"
echo "• App Connect IA: https://developers.facebook.com/apps/670209849105494"
echo "• Política de Privacidade: https://connectia.agenciapixel.digital/privacy-policy.html"
echo "• Termos de Uso: https://connectia.agenciapixel.digital/terms.html"
echo "• Exclusão de Dados: https://connectia.agenciapixel.digital/data-deletion.html"
echo ""

echo -e "${GREEN}✅ TODAS AS URLs ESTÃO PRONTAS PARA CONFIGURAÇÃO NO META!${NC}"
echo ""
echo -e "${BLUE}🎯 O app Connect IA agora está em conformidade total com os requisitos do Meta for Developers.${NC}"
