#!/bin/bash

echo "🔐 VERIFICAÇÃO PROVEDOR DE TECNOLOGIA - META"
echo "============================================"
echo ""

# Cores
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${RED}⚠️  PRAZO IMPORTANTE: ATÉ 15/12/2025${NC}"
echo -e "${BLUE}Empresa: Pixel - Agência Digital${NC}"
echo -e "${BLUE}Objetivo: Evitar restrições ao app Connect IA${NC}"
echo ""

echo -e "${GREEN}📋 RESPOSTAS PARA O FORMULÁRIO${NC}"
echo ""

echo -e "${YELLOW}1️⃣ DESCRIÇÃO DA EMPRESA:${NC}"
echo "☑️ Agência"
echo "☑️ Plataforma de SaaS"
echo ""

echo -e "${YELLOW}2️⃣ USO DA PLATAFORMA DE DADOS:${NC}"
echo ""
echo -e "${BLUE}RESPOSTA RECOMENDADA:${NC}"
echo ""
echo "A Pixel - Agência Digital desenvolve e opera o Connect IA, uma"
echo "plataforma de CRM e automação que utiliza dados da Meta para"
echo "fornecer serviços de gestão comercial aos nossos clientes."
echo ""
echo "SERVIÇO FORNECIDO:"
echo "O Connect IA é uma plataforma completa de CRM que permite às"
echo "empresas gerenciar conversas do WhatsApp Business de forma"
echo "centralizada, automatizar campanhas de marketing no Instagram,"
echo "organizar leads e prospects em um sistema unificado, gerar"
echo "relatórios e métricas de vendas, e integrar múltiplos canais"
echo "de comunicação (WhatsApp, Instagram, Facebook)."
echo ""
echo "COMO USAMOS OS DADOS:"
echo "Utilizamos os dados da plataforma Meta para receber e processar"
echo "mensagens do WhatsApp Business via webhook, acessar dados básicos"
echo "do Instagram para automação de campanhas, sincronizar informações"
echo "de contatos e conversas, gerar insights e relatórios para nossos"
echo "clientes, e facilitar o atendimento ao cliente de forma integrada."
echo ""
echo "COMO OS CLIENTES UTILIZAM:"
echo "Nossos clientes (empresas e empreendedores) utilizam o Connect IA"
echo "para centralizar todas as conversas em uma única plataforma,"
echo "automatizar respostas e campanhas de marketing, organizar e"
echo "acompanhar leads de forma eficiente, aumentar vendas através de"
echo "melhor gestão de relacionamento, e economizar tempo na gestão de"
echo "múltiplos canais."
echo ""
echo "O Connect IA atua como intermediário tecnológico, facilitando a"
echo "gestão comercial através de integrações seguras com WhatsApp"
echo "Business e Instagram, sempre respeitando as políticas de"
echo "privacidade e uso de dados."
echo ""

echo -e "${YELLOW}3️⃣ GESTÃO DE PORTFÓLIOS EMPRESARIAIS:${NC}"
echo "☑️ No (Não)"
echo ""

echo -e "${YELLOW}4️⃣ IDENTIFICAÇÕES DE PORTFÓLIOS:${NC}"
echo "Não se aplica - nossa empresa não gerencia múltiplos portfólios empresariais."
echo ""

echo -e "${YELLOW}5️⃣ WEBSITE DA EMPRESA:${NC}"
echo "https://agenciapixel.digital"
echo ""

echo -e "${GREEN}📋 CHECKLIST DE PREPARAÇÃO${NC}"
echo ""
echo -e "${BLUE}Antes de Enviar:${NC}"
echo "  [ ] Website atualizado com informações completas"
echo "  [ ] Descrição clara dos serviços da empresa"
echo "  [ ] Informações de contato válidas"
echo "  [ ] Portfolio de projetos recentes"
echo "  [ ] Página sobre Connect IA (recomendado)"
echo ""

echo -e "${BLUE}Informações Adicionais Úteis:${NC}"
echo "  [ ] CNPJ da empresa"
echo "  [ ] Endereço comercial"
echo "  [ ] Telefone de contato"
echo "  [ ] Email corporativo"
echo "  [ ] Certificações (se houver)"
echo ""

echo -e "${GREEN}🎯 PONTOS-CHAVE PARA ENFATIZAR${NC}"
echo ""
echo "1. ✅ EXPERIÊNCIA EM TECNOLOGIA:"
echo "   • Desenvolvimento de software"
echo "   • Integração com APIs"
echo "   • Gestão de dados"
echo ""
echo "2. ✅ FOCO NO CLIENTE:"
echo "   • Soluções personalizadas"
echo "   • Suporte técnico"
echo "   • Resultados mensuráveis"
echo ""
echo "3. ✅ CONFORMIDADE:"
echo "   • Respeito às políticas do Meta"
echo "   • Proteção de dados"
echo "   • Transparência"
echo ""
echo "4. ✅ INOVAÇÃO:"
echo "   • Tecnologia de ponta"
echo "   • Automação inteligente"
echo "   • Integração multi-canal"
echo ""

echo -e "${GREEN}📞 INFORMAÇÕES DE CONTATO${NC}"
echo ""
echo -e "${BLUE}Para o Formulário:${NC}"
echo "Empresa: Pixel - Agência Digital"
echo "Website: https://agenciapixel.digital"
echo "Email: contato@agenciapixel.digital"
echo "Telefone: [Incluir telefone da empresa]"
echo "Endereço: [Incluir endereço completo]"
echo ""

echo -e "${YELLOW}⚠️  IMPORTANTES CONSIDERAÇÕES${NC}"
echo ""
echo "1. 🔍 TRANSPARÊNCIA:"
echo "   • Seja honesto sobre os serviços oferecidos"
echo "   • Descreva claramente como os dados são usados"
echo "   • Evite jargões técnicos desnecessários"
echo ""
echo "2. 🎯 ESPECIFICIDADE:"
echo "   • Foque no Connect IA como produto principal"
echo "   • Explique o valor para os clientes finais"
echo "   • Destaque a conformidade com políticas"
echo ""
echo "3. 💼 PROFISSIONALISMO:"
echo "   • Use linguagem clara e profissional"
echo "   • Evite promessas exageradas"
echo "   • Demonstre experiência técnica"
echo ""

echo -e "${GREEN}🎯 PRÓXIMOS PASSOS${NC}"
echo ""
echo -e "${BLUE}Após Envio:${NC}"
echo "1. Aguardar análise do Meta (7-14 dias)"
echo "2. Responder questionamentos se solicitado"
echo "3. Fornecer documentação adicional se necessário"
echo "4. Manter website atualizado"
echo "5. Acompanhar status da verificação"
echo ""
echo -e "${BLUE}Monitoramento:${NC}"
echo "• Verificar email regularmente"
echo "• Acompanhar status no Meta for Developers"
echo "• Manter documentação atualizada"
echo "• Responder rapidamente a solicitações"
echo ""

echo -e "${RED}⚠️  LEMBRE-SE:${NC}"
echo "Esta verificação é essencial para manter o acesso completo"
echo "às APIs do Meta e evitar restrições ao Connect IA."
echo ""

echo -e "${GREEN}✅ FORMULÁRIO PRONTO PARA PREENCHIMENTO!${NC}"
echo ""
echo -e "${BLUE}📚 Documentação completa disponível em:${NC}"
echo "docs/VERIFICACAO_PROVEDOR_TECNOLOGIA_META.md"
